MMCA-3963 : Non-compliance : Issue#4 - Two h1s
hmrc/customs-manage-authorities-frontend pull request #106
Opened 2023-05-10 16:28 UTC by sameerhmrc

JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-3963

2023-05-10 16:31 UTC, bsgangapat approved these changes

2023-05-10 16:40 UTC, wg-hmrc commented on app/views/AccountsView.scala.html
> +        h2: components.h2,
@sameerhmrc please keep it as H1.. this file was fixed

2023-05-10 16:42 UTC, wg-hmrc requested changes
the change will cause accessibility issues

2023-05-10 17:11 UTC, sameerhmrc commented on app/views/AccountsView.scala.html
> +        h2: components.h2,
@wg-hmrc this has now been reverted

2023-05-10 17:12 UTC, sameerhmrc commented
> the change will cause accessibility issues

changes incorporated

2023-05-11 08:11 UTC, wg-hmrc approved these changes

2023-05-11 08:16 UTC, merged